/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Mike
 */
public class View_Rentas extends javax.swing.JPanel {

    /**
     * Creates new form View_Rentas
     */
    public View_Rentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_total_renta = new javax.swing.JTextField();
        jl_formato = new javax.swing.JLabel();
        jtf_formato = new javax.swing.JTextField();
        jl_total_renta = new javax.swing.JLabel();
        jtf_costo_por_dia = new javax.swing.JTextField();
        jtf_dias = new javax.swing.JTextField();
        jl_costo_por_dia = new javax.swing.JLabel();
        jtf_id_renta = new javax.swing.JTextField();
        jl_id_renta = new javax.swing.JLabel();
        jl_dias = new javax.swing.JLabel();
        jb_editar = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jtf_id_cliente = new javax.swing.JTextField();
        jl_id_cliente = new javax.swing.JLabel();
        jl_id_pelicula = new javax.swing.JLabel();
        jtf_id_pelicula = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 173, 255));

        jtf_total_renta.setBackground(new java.awt.Color(51, 173, 255));
        jtf_total_renta.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_total_renta.setForeground(new java.awt.Color(255, 255, 255));
        jtf_total_renta.setPreferredSize(new java.awt.Dimension(120, 27));

        jl_formato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_formato.setForeground(new java.awt.Color(255, 255, 255));
        jl_formato.setText("Formato:");

        jtf_formato.setBackground(new java.awt.Color(51, 173, 255));
        jtf_formato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_formato.setForeground(new java.awt.Color(255, 255, 255));
        jtf_formato.setPreferredSize(new java.awt.Dimension(120, 27));

        jl_total_renta.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_total_renta.setForeground(new java.awt.Color(255, 255, 255));
        jl_total_renta.setText("Total renta:");

        jtf_costo_por_dia.setBackground(new java.awt.Color(51, 173, 255));
        jtf_costo_por_dia.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_costo_por_dia.setForeground(new java.awt.Color(255, 255, 255));
        jtf_costo_por_dia.setPreferredSize(new java.awt.Dimension(120, 27));

        jtf_dias.setBackground(new java.awt.Color(51, 173, 255));
        jtf_dias.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_dias.setForeground(new java.awt.Color(255, 255, 255));
        jtf_dias.setPreferredSize(new java.awt.Dimension(120, 27));

        jl_costo_por_dia.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_costo_por_dia.setForeground(new java.awt.Color(255, 255, 255));
        jl_costo_por_dia.setText("Costo X Día:");

        jtf_id_renta.setBackground(new java.awt.Color(51, 173, 255));
        jtf_id_renta.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_id_renta.setForeground(new java.awt.Color(255, 255, 255));
        jtf_id_renta.setPreferredSize(new java.awt.Dimension(120, 27));

        jl_id_renta.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_id_renta.setForeground(new java.awt.Color(255, 255, 255));
        jl_id_renta.setText("ID Renta:");

        jl_dias.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_dias.setForeground(new java.awt.Color(255, 255, 255));
        jl_dias.setText("Días:");

        jb_editar.setBackground(new java.awt.Color(51, 173, 255));
        jb_editar.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_editar.setForeground(new java.awt.Color(255, 255, 255));
        jb_editar.setText("Editar");

        jb_primero.setBackground(new java.awt.Color(51, 173, 255));
        jb_primero.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_primero.setForeground(new java.awt.Color(255, 255, 255));
        jb_primero.setText("|<");

        jb_anterior.setBackground(new java.awt.Color(51, 173, 255));
        jb_anterior.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jb_anterior.setText("<<");

        jb_nuevo.setBackground(new java.awt.Color(51, 173, 255));
        jb_nuevo.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jb_nuevo.setText("Nuevo");

        jb_guardar.setBackground(new java.awt.Color(51, 173, 255));
        jb_guardar.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");

        jb_borrar.setBackground(new java.awt.Color(51, 173, 255));
        jb_borrar.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_borrar.setForeground(new java.awt.Color(255, 255, 255));
        jb_borrar.setText("Borrar");

        jb_ultimo.setBackground(new java.awt.Color(51, 173, 255));
        jb_ultimo.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_ultimo.setForeground(new java.awt.Color(255, 255, 255));
        jb_ultimo.setText(">|");

        jb_siguiente.setBackground(new java.awt.Color(51, 173, 255));
        jb_siguiente.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jb_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jb_siguiente.setText(">>");
        jb_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_siguienteActionPerformed(evt);
            }
        });

        jtf_id_cliente.setBackground(new java.awt.Color(51, 173, 255));
        jtf_id_cliente.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_id_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jtf_id_cliente.setPreferredSize(new java.awt.Dimension(120, 27));

        jl_id_cliente.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_id_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jl_id_cliente.setText("ID Cliente:");

        jl_id_pelicula.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jl_id_pelicula.setForeground(new java.awt.Color(255, 255, 255));
        jl_id_pelicula.setText("ID Pelicula:");

        jtf_id_pelicula.setBackground(new java.awt.Color(51, 173, 255));
        jtf_id_pelicula.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jtf_id_pelicula.setForeground(new java.awt.Color(255, 255, 255));
        jtf_id_pelicula.setPreferredSize(new java.awt.Dimension(120, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id_renta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_id_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_total_renta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_total_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_formato)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_dias)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_dias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_costo_por_dia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_costo_por_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id_pelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_nuevo)
                            .addComponent(jb_borrar))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_guardar)
                            .addComponent(jb_editar))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_primero)
                        .addGap(18, 18, 18)
                        .addComponent(jb_anterior)
                        .addGap(18, 18, 18)
                        .addComponent(jb_siguiente)
                        .addGap(18, 18, 18)
                        .addComponent(jb_ultimo)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jb_anterior)
                                .addComponent(jb_siguiente)
                                .addComponent(jb_ultimo)
                                .addComponent(jb_primero))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_nuevo)
                                    .addComponent(jb_editar))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb_borrar)
                                    .addComponent(jb_guardar))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_id_renta)
                            .addComponent(jtf_id_renta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_id_cliente)
                            .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_id_pelicula)
                            .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_formato)
                            .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_costo_por_dia)
                            .addComponent(jtf_costo_por_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_dias)
                            .addComponent(jtf_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_total_renta)
                            .addComponent(jtf_total_renta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_siguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_anterior;
    public javax.swing.JButton jb_borrar;
    public javax.swing.JButton jb_editar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_primero;
    public javax.swing.JButton jb_siguiente;
    public javax.swing.JButton jb_ultimo;
    public javax.swing.JLabel jl_costo_por_dia;
    public javax.swing.JLabel jl_dias;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_id_cliente;
    public javax.swing.JLabel jl_id_pelicula;
    public javax.swing.JLabel jl_id_renta;
    public javax.swing.JLabel jl_total_renta;
    public javax.swing.JTextField jtf_costo_por_dia;
    public javax.swing.JTextField jtf_dias;
    public javax.swing.JTextField jtf_formato;
    public javax.swing.JTextField jtf_id_cliente;
    public javax.swing.JTextField jtf_id_pelicula;
    public javax.swing.JTextField jtf_id_renta;
    public javax.swing.JTextField jtf_total_renta;
    // End of variables declaration//GEN-END:variables
}
